server:
    port: 8080
logging:
    level:
    root: WARN
spring:
    datasource:
        dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
        url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8
        databaseName: 
        serverName: 
        username: root
        password: 
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        database: MYSQL
        openInView: false
        show_sql: false
        generate-ddl: true
        hibernate:
            ddl-auto: create
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false